spring.datasource.url=${DB_URL:${SPRING_DATASOURCE_URL}}
spring.datasource.username=${DB_USER:${SPRING_DATASOURCE_USERNAME}}
spring.datasource.password=${DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver
