spring.datasource.url=jdbc:postgresql://localhost:5432/local-database-1
spring.datasource.username=postgres
spring.datasource.password=localpass
spring.datasource.driver-class-name=org.postgresql.Driver